name: Bluesky FeedBot
on:
  schedule:
    # This will run every hour
    - cron: "0 * * * *"
  workflow_dispatch:
jobs:
  rss-to-bluesky:
    runs-on: ubuntu-latest
    steps:
      - name: Generate cache key
        uses: actions/github-script@d7906e4ad0b1822421a7e6a35d5ca353c962f410 # v6
        id: generate-key
        with:
          script: |
            core.setOutput('cache-key', new Date().valueOf())
      - name: Retrieve cache
        uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4
        with:
          path: ${{ github.workspace }}/blueskyfeedbot
          key: feed-cache-${{ steps.generate-key.outputs.cache-key }}
          restore-keys: feed-cache-
      - name: GitHub
        uses: "joschi/blueskyfeedbot@ed4ead7c92564213b9004baf11f615c0d65c4fa8" # v0.0.3
        with:
          # This is the RSS feed you want to publish
          rss-feed: https://nf-co.re/blog/rss.xml
          # Template of status posted to Bluesky (Handlebars)
          template: |
            New blog post! {{item.title}}
            {{item.link}}
          # This is your service URL (optional)
          service-url: https://bsky.social
          # This is the Bluesky username (example: username.bsky.social)
          username: "nf-co.re"
          # This is the app password you created earlier
          password: ${{ secrets.FEED_TO_BLUESKY }}
          # This is a path to the cache file, using the above cache path
          cache-file: ${{ github.workspace }}/blueskyfeedbot/cache.json
          initial-post-limit: 0
